# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-10-18 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_card',
            field=models.CharField(max_length=20, null=True, verbose_name='身份证号'),
        ),
        migrations.AddField(
            model_name='user',
            name='real_name',
            field=models.CharField(max_length=32, null=True, verbose_name='真实姓名'),
        ),
    ]
