# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-10-18 12:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homes', '0005_houseimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('begin_date', models.DateField(verbose_name='预订的起始时间')),
                ('end_date', models.DateField(verbose_name='结束时间')),
                ('days', models.IntegerField(verbose_name='预订的总天数')),
                ('house_price', models.IntegerField(verbose_name='房屋单价')),
                ('amount', models.IntegerField(verbose_name='订单总金额')),
                ('status', models.SmallIntegerField(choices=[(0, 'WAIT_ACCEPT'), (1, 'WAIT_PAYMENT'), (2, 'PAID'), (3, 'WAIT_COMMENT'), (4, 'COMPLETE'), (5, 'CANCELED'), (6, 'REJECTED')], db_index=True, default=0, verbose_name='订单状态')),
                ('comment', models.TextField(default='', verbose_name='订单的评论信息或者拒单原因')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homes.House', verbose_name='预订的房间编号')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='下订单的用户编号')),
            ],
            options={
                'db_table': 'tb_order',
            },
        ),
    ]
