# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-10-18 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(null=True, verbose_name='订单的评论信息或者拒单原因'),
        ),
    ]
